package dev.hspl.hspl2shop.common.value;

public enum UserAction {
    REGISTER_NEW_ADDRESS,
    EDIT_ADDRESS,
    DELETE_ADDRESS,

    ADMIN_FETCH_CATEGORIES,
    ADMIN_REGISTER_NEW_CATEGORY,
    ADMIN_EDIT_CATEGORY,
    ADMIN_DELETE_CATEGORY,

    ADMIN_REGISTER_NEW_PRODUCT,
    ADMIN_EDIT_PRODUCT,
    ADMIN_CHANGE_PRODUCT_VISIBILITY,
    ADMIN_REGISTER_VARIANT_FOR_PRODUCT,
    ADMIN_DELETE_VARIANT_FROM_PRODUCT,
    ADMIN_EDIT_VARIANT_OF_PRODUCT,
    ADMIN_CHANGE_PRODUCT_VARIANT_VISIBILITY,
    ADMIN_UPDATE_PRODUCT_PRICE,
    ADMIN_UPDATE_VARIANT_STOCK
}
